# Generated by Django 4.0.3 on 2022-03-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_and_more_app', '0004_rename_ingredient_calories_ingredientcalories_ingredient_calories_per_100_gr_or_ml_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptingredient',
            old_name='ingredient_calories',
            new_name='ingredient_name_frk',
        ),
        migrations.RenameField(
            model_name='receiptingredient',
            old_name='recipe',
            new_name='recipe_frk',
        ),
        migrations.AlterModelTable(
            name='receiptingredient',
            table='receipt_ingredient',
        ),
    ]
