# Generated by Django 4.0.3 on 2022-03-14 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes_and_more_app', '0005_rename_ingredient_calories_receiptingredient_ingredient_name_frk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipereviews',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
