# Generated by Django 4.0.3 on 2022-03-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_and_more_app', '0008_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcalories',
            name='optional_allergens_2',
            field=models.CharField(blank=True, choices=[('GLUTEN', 'Gluten'), ('EGGS', 'Eggs'), ('LACTOSE', 'lactose'), ('NUTS', 'Nuts'), ('PEANUTS', 'Peanuts'), ('SESAME SEEDS', 'Sesame Seeds'), ('SOY', 'Soy'), ('NON', 'Non')], max_length=128, null=True),
        ),
    ]
